name: Update API documentation

on: push
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  build:
    name: Build and update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout V8, create documentation, and push changes
        uses: ./.github/actions/docker-doxygen

