name: Update API documentation

on: push
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  build:
    name: Build and update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install doxygen graphviz ttf-freefont git rsync      

#      - name: Generate documentation
#        uses: ./.github/actions/docker-doxygen
#      - name: Commit and push
#        run: |
#          git config --global user.name "V8 API docs updater"
#          git config --global user.email "v8-dev+api@googlegroups.com"
#          git commit -am "Automated docs build."
#          git push
