name: Update API documentation

on:
  schedule:
    -cron: '*/15 * * * *'

jobs:
  build:
    name: Build and update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


