name: Update API documentation

on: push
#  schedule:
#    - cron: '*/15 * * * *'

jobs:
  build:
    name: Build and update documentation
    runs-on: ubuntu-latest
    container:
      image: docker://python:3.7-alpine
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apk add doxygen graphviz ttf-freefont git rsync
      - name: Build docs
        run: |
          python update.py
      - name: Commit and push
        run: |
          git config --global user.name "V8 API docs updater"
          git config --global user.email "v8-dev+api@googlegroups.com"
          git commit -am "Automated docs build."
          git push
